version: '3.9'

services:
  app:
    container_name: app
    build: ./backend
    ports:
      - "8080:7082"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=justinaio
    volumes:  
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

