package io.justina.h106javareact.domain.entities.enums;

public enum MedicalLicense {
    MATRICULA_NACIONAL,
    MATRICULA_DE_BUENOS_AIRES,
    MATRICULA_DE_CATAMARCA,
    MATRICULA_DE_CHACO,
    MATRICULA_DE_CHUBUT,
    MATRICULA_DE_CORDOBA,
    MATRICULA_DE_CORRIENTES,
    MATRICULA_DE_ENTRE_RIOS,
    MATRICULA_DE_FORMOSA,
    MATRICULA_DE_JUJUY,
    MATRICULA_DE_LA_PAMPA,
    MATRICULA_DE_LA_RIOJA,
    MATRICULA_DE_MENDOZA,
    MATRICULA_DE_MISIONES,
    MATRICULA_DE_NEUQUEN,
    MATRICULA_DE_RIO_NEGRO,
    MATRICULA_DE_SALTA,
    MATRICULA_DE_SAN_JUAN,
    MATRICULA_DE_SAN_LUIS,
    MATRICULA_DE_SANTA_CRUZ,
    MATRICULA_DE_SANTA_FE,
    MATRICULA_DE_SANTIAGO_DEL_ESTERO,
    MATRICULA_DE_TIERRA_DEL_FUEGO,
    MATRICULA_DE_TUCUMAN,
    MATRICULA_DE_CIUDAD_AUTONOMA_DE_BUENOS_AIRES;
}
